# Generated by Django 3.2.4 on 2021-06-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20210626_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='place',
            field=models.CharField(blank=True, max_length=30, verbose_name='place'),
        ),
    ]
